### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by iamzeid** [sildar/potara#12]
Hello,
I tried to test the library on 4 documents `["1.txt", "2.txt", "3.txt", "4.txt"]` using this code:

```
from potara.summarizer import Summarizer
from potara.document import Document
import nltk
from nltk import word_tokenize, sent_tokenize

s = Summarizer(minbigramcount=4)

# Adding docs, preprocessing them and computing some infos for the summarizer
s.setDocuments([Document("data/" + str(i) + '.txt')
                for i in range(1, 5)])

# Summarizing, where the actual work is done
s.summarize()

# You can then print the summary
print(s.summary)

```

But the I got this: 
```
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\hatemylife\hate\lib\site-packages\pulp\pulp.py:1199: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")
['The biggest news with Elon Musk ’ s tweet is that SpaceX eventually plans to produce fuel this way on Earth.']
Exception ignored in: <function Pool.__del__ at 0x0000017FFF66A550>
Traceback (most recent call last):
  File "c:\python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Pool.__del__ at 0x0000017FFF66A550>
Traceback (most recent call last):
  File "c:\python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Pool.__del__ at 0x0000017FFF66A550>
Traceback (most recent call last):
  File "c:\python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Pool.__del__ at 0x0000017FFF66A550>
Traceback (most recent call last):
  File "c:\python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Pool.__del__ at 0x0000017FFF66A550>
Traceback (most recent call last):
  File "c:\python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Pool.__del__ at 0x0000017FFF66A550>
Traceback (most recent call last):
  File "c:\python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Pool.__del__ at 0x0000017FFF66A550>
Traceback (most recent call last):
  File "c:\python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Pool.__del__ at 0x0000017FFF66A550>
Traceback (most recent call last):
  File "c:\python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Pool.__del__ at 0x0000017FFF66A550>
Traceback (most recent call last):
  File "c:\python38\lib\multiprocessing\pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
del__
    self._change_notifier.put(None)
  File "c:\python38\lib\multiprocessing\queues.py", line 365, in put
    self._writer.send_bytes(obj)
  File "c:\python38\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python38\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
OSError: [WinError 6] The handle is invalid
```

What should I do to solve this problem?

Notes:

* I use Windows 10
* I get same result on a virtual environment.

* Data folder contains:

1. english-left3words-distsim.tagger
2. stanford-postagger.jar
3. english.pickle
4. The 4 documents ["1.txt", "2.txt", "3.txt", "4.txt"]

**Comment by sildar** [comment]
Hi! Thanks for your interest in potara.

This is a new one. Potara hasn't be tested a lot on Windows and you're using python 3.8 that hasn't really been tested either. It seems like the problem comes from pulp as this is where the multiprocessing should happen. I realize that pulp is the only dependency that has no strict version set, it was at 2.0 when it was last tested.

I'm not sure I can dig a lot deeper into this right now, maybe if it's easy for you to test with python 3.6 and pulp2.0 in a virtualenv, this would give us more information.

Your data folder is probably not the issue.

**Comment by iamzeid** [comment]
Hello Sir,
After I saw your reply, I started running the code with `Python 3.6` and `Pulp 2.0` in a Virtual Environment. This made the `WinError 6` disappear, but I also got this result:

```
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial  
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial  
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial  
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\pulp\pulp.py:1137: UserWarning: Spaces are not permitted in the name. Converted to '_'     
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial  
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\iZeid\Desktop\newworld\venv\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial  
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")

['Elon Musk, seen here arriving at a New York federal court in April 2019, has recently become the world ’ s wealthiest person.']
```

Now my question is:
- What does the `Chunkize Warning` mean? Is it something to worry about?
- The summary is only one sentence, and it is different every time I run the code (With The Same Input). Is that normal, or is there a problem?

**Thank you for your time, and I appreciate your support.**

**Comment by sildar** [comment]
Thanks for testing.

The warnings are nothing to worry about. You can disable them if you want with:

```
import warnings
warnings.filterwarnings(action='ignore', category=UserWarning, module='gensim')

import gensim
```
[source for disabling the warning](https://stackoverflow.com/questions/41658568/chunkize-warning-while-installing-gensim)

> The summary **is only one sentence**, and it is different every time I run the code

Are your 4 documents extremely similar? Potara first groups very similar sentences and fuses those to obtain a single more condensed or more informative sentence. It then chooses one sentence (fused or original) from each set of similar/fused sentences. If your documents are very short with very similar sentences, it is possible that only one sentence is output. Otherwise the output should be ~8 sentences (~100 words).

It has been created for sets of ~10 or more documents and it's possible that some parameters should change for smaller datasets.

> The summary is only one sentence, and **it is different every time I run the code**

This is also possible if different sentences contain the same level of informativeness with the same number of words. This should rarely occur in real world use cases or be very limited.

**Comment by iamzeid** [comment]
Okay, I think that's it. Thank you for your time.
